apiVersion: v2
name: whatsmyip
description: Returns clients public ip
version: 0.1.1
type: application
appVersion: "1.22"
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
